package auth

import (
	"crypto/rand"
	"encoding/base64"
)

// GenerateNonce returns an array of cryptographically randomly generated bytes with the given entropy.
func GenerateNonce(entropy uint) []byte {
	nonce := make([]byte, entropy)
	_, _ = rand.Read(nonce) // never returns an error according to docs.
	return nonce
}

// GenerateURLSafeNonce returns a base64 url encoded nonce with the given bytes of entropy.
func GenerateURLSafeNonce(entropy uint) string {
	nonce := GenerateNonce(entropy)
	return base64.RawURLEncoding.EncodeToString(nonce)
}
